# Generated by Django 3.1.7 on 2021-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210705_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='country',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='level',
            new_name='language_level',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language_name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='skill_level',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
