# Generated by Django 3.1.7 on 2021-07-19 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210719_1056'),
        ('account', '0017_auto_20210719_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='basic_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.basicpacket'),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='premium_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.premiumpacket'),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='standard_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.standardpacket'),
        ),
    ]
