# Generated by Django 3.1.7 on 2021-07-25 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210721_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='project',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='feedback',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='feedback',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
