# Generated by Django 3.1.7 on 2021-07-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
