# Generated by Django 3.1.7 on 2021-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210727_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
    ]
