# Generated by Django 3.1.7 on 2021-07-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210730_1919'),
        ('account', '0026_account_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='basic_packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.basicpacket'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='premium_packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.premiumpacket'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='standard_packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.standardpacket'),
        ),
    ]
