# Generated by Django 3.1.7 on 2021-07-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210703_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostSubCategories',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='PostCategories',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='subcategories',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='categories',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='categories',
            new_name='country',
        ),
    ]
