# Generated by Django 3.1.7 on 2021-07-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210703_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='country',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='city',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='country',
            new_name='categories',
        ),
    ]
