# Generated by Django 3.1.7 on 2021-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210703_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categories',
            new_name='category',
        ),
    ]
