# Generated by Django 3.1.7 on 2021-07-03 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='budget',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='deadline',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
