# Generated by Django 3.1.7 on 2021-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210703_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='deadline',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
