# Generated by Django 3.1.7 on 2021-07-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210703_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='deadline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
