# Generated by Django 3.1.7 on 2021-07-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210725_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(default='avail', max_length=50),
        ),
    ]
