# Generated by Django 3.1.7 on 2021-07-15 12:35

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='image',
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_name', models.CharField(max_length=100)),
                ('packet_desc', models.CharField(max_length=100)),
                ('delivery', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField()),
                ('price', models.BigIntegerField()),
                ('packet_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicepost')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.models.upload_location)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.servicepost')),
            ],
        ),
    ]
