# Generated by Django 3.1.7 on 2021-07-17 11:33

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210704_0650'),
        ('service', '0002_auto_20210715_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('basic_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('basic_price', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_name', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_price', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('standard_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('standard_price', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='service_category',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=service.models.upload_location, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='service_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory'),
        ),
        migrations.DeleteModel(
            name='Packet',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceSubCategory',
        ),
        migrations.AddField(
            model_name='standardpacket',
            name='standard_packet_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicepost'),
        ),
        migrations.AddField(
            model_name='premiumpacket',
            name='premium_packet_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicepost'),
        ),
        migrations.AddField(
            model_name='basicpacket',
            name='basic_packet_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicepost'),
        ),
    ]
