# Generated by Django 3.1.7 on 2021-07-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210717_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='service_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='servicepost',
            old_name='service_subcategory',
            new_name='subcategory',
        ),
    ]
