# Generated by Django 3.1.7 on 2021-07-17 12:58

from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210704_0650'),
        ('service', '0005_auto_20210717_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=service.models.upload_location),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
