# Generated by Django 3.1.7 on 2021-07-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210717_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpacket',
            name='tipe_packet',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumpacket',
            name='tipe_packet',
            field=models.CharField(default='premium', max_length=20),
        ),
        migrations.AddField(
            model_name='standardpacket',
            name='tipe_packet',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
