# Generated by Django 3.1.7 on 2021-07-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210719_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpacket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='premiumpacket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standardpacket',
            name='id',
        ),
        migrations.AddField(
            model_name='basicpacket',
            name='basic_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumpacket',
            name='premium_id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardpacket',
            name='standard_id',
            field=models.IntegerField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
