# Generated by Django 3.1.7 on 2021-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210719_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpacket',
            name='basic_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premiumpacket',
            name='premium_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='standardpacket',
            name='standard_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
